### ISSUE TITLE
 Compilation failing with GCC 7.1.1

### ISSUE THREAD

**Issue by seanpianka** [ethereum/cpp-ethereum#4333]
```bash
$ uname -a
Linux Caldera 4.12.4-1-ARCH #1 SMP PREEMPT Fri Jul 28 18:54:18 UTC 2017 x86_64 GNU/Linux
```

and `gcc version 7.1.1 20170630 (GCC)`

```
Scanning dependencies of target ethash
[ 32%] Building C object libethereum/libethash/CMakeFiles/ethash.dir/io.c.o
[ 32%] Building C object libethereum/libethash/CMakeFiles/ethash.dir/internal.c.o
/tmp/packerbuild-1000/ethereum/ethereum/src/ethereum/libethereum/libethash/internal.c: In function ‘ethash_full_new_internal’:
/tmp/packerbuild-1000/ethereum/ethereum/src/ethereum/libethereum/libethash/internal.c:434:6: error: this statement may fall through [-Werror=implicit-fallthrough=]
   if (ethash_io_prepare(dirname, seed_hash, &f, (size_t)full_size, true) != ETHASH_IO_MEMO_MISMATCH) {
      ^
/tmp/packerbuild-1000/ethereum/ethereum/src/ethereum/libethereum/libethash/internal.c:439:2: note: here
  case ETHASH_IO_MEMO_MISMATCH:
  ^~~~
/tmp/packerbuild-1000/ethereum/ethereum/src/ethereum/libethereum/libethash/internal.c: In function ‘ethash_light_compute_internal’:
/tmp/packerbuild-1000/ethereum/ethereum/src/ethereum/libethereum/libethash/internal.c:233:24: error: ‘tmp_node’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
      mix[n].words[w] = fnv_hash(mix[n].words[w], dag_node->words[w]);
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/packerbuild-1000/ethereum/ethereum/src/ethereum/libethereum/libethash/internal.c:233:24: error: ‘*((void *)&tmp_node+16)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
/tmp/packerbuild-1000/ethereum/ethereum/src/ethereum/libethereum/libethash/internal.c:233:24: error: ‘*((void *)&tmp_node+32)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
/tmp/packerbuild-1000/ethereum/ethereum/src/ethereum/libethereum/libethash/internal.c:233:24: error: ‘*((void *)&tmp_node+48)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
/tmp/packerbuild-1000/ethereum/ethereum/src/ethereum/libethereum/libethash/internal.c:233:24: error: ‘tmp_node’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
/tmp/packerbuild-1000/ethereum/ethereum/src/ethereum/libethereum/libethash/internal.c:233:24: error: ‘*((void *)&tmp_node+16)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
/tmp/packerbuild-1000/ethereum/ethereum/src/ethereum/libethereum/libethash/internal.c:233:24: error: ‘*((void *)&tmp_node+32)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
/tmp/packerbuild-1000/ethereum/ethereum/src/ethereum/libethereum/libethash/internal.c:233:24: error: ‘*((void *)&tmp_node+48)’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
cc1: all warnings being treated as errors
make[2]: *** [libethereum/libethash/CMakeFiles/ethash.dir/build.make:87: libethereum/libethash/CMakeFiles/ethash.dir/internal.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1014: libethereum/libethash/CMakeFiles/ethash.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by chfast** [comment]
Builds with GCC 7.2 are fine. Can you test again?
