### ISSUE TITLE
ExtVMFace.h:262:1: error: expected class-name before ‘{’ token

### ISSUE THREAD

**Issue by moneroexamples** [ethereum/cpp-ethereum#4429]
Trying to compile on Ubuntu 16.04 current master, and getting this error:

```
In file included from /home/mwo/cpp-ethereum/libethcore/SealEngine.cpp:24:0:
/home/mwo/cpp-ethereum/libdevcore/../libevm/ExtVMFace.h:262:1: error: expected class-name before ‘{’ token
 {
 ^
libethcore/CMakeFiles/ethcore.dir/build.make:110: recipe for target 'libethcore/CMakeFiles/ethcore.dir/SealEngine.cpp.o' failed
make[2]: *** [libethcore/CMakeFiles/ethcore.dir/SealEngine.cpp.o] Error 1
CMakeFiles/Makefile2:662: recipe for target 'libethcore/CMakeFiles/ethcore.dir/all' failed
make[1]: *** [libethcore/CMakeFiles/ethcore.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by moneroexamples** [comment]
Works now. Closing.
