### PR TITLE
Fix QT 5.5 Build

### PR DESCRIPTION
**Pull request by LefterisJP**
In QT 5.5 `Mono` is a reserved preprocessor define and as such building
with it fails.

```
In file included from /usr/include/qt/QtGui/qvalidator.h:42:
/usr/include/qt/QtCore/qlocale.h:407:9: error: expected identifier
        Mono = 337,
        ^
/home/lefteris/ew/cpp-ethereum/alethzero/Context.h:36:14: note: expanded from macro 'Mono'
#define Mono "font-family: Ubuntu Mono, Monospace, Lucida Console, Courier New; font-weight: bold; "
             ^
1 error generated.
alethzero/CMakeFiles/alethzero.dir/build.make:158: recipe for target 'alethzero/CMakeFiles/alethzero.dir/Context.cpp.o' failed
make[2]: *** [alethzero/CMakeFiles/alethzero.dir/Context.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

Switching the macros in `alethzero/Context.h` to follow Coding Standards
fixes this discrepancy and allows us to build with QT 5.5.

### CODE REVIEW

**Comment by LefterisJP** [comment]
rebased on develop after whizz branch merging
